apiVersion: apps/v1
kind: Deployment
metadata:
 name: session13-app
 namespace: session13
spec:
 replicas: 1
 selector:
  matchLabels: 
   app: session13-app
 template:
  metadata:
   labels: 
    app: session13-app
  spec: 
   containers:
   - name: sessio13-app
     image: uzairchini/session13-app:latest
     ports: 
     - containerPort: 5000
